# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1111, 859)
        Dialog.setMinimumSize(QtCore.QSize(673, 415))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setAutoFillBackground(False)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1091, 841))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.console = QtWidgets.QLabel(self.tab)
        self.console.setGeometry(QtCore.QRect(290, 280, 761, 291))
        self.console.setFrameShape(QtWidgets.QFrame.Box)
        self.console.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.console.setText("")
        self.console.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.console.setWordWrap(True)
        self.console.setObjectName("console")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(150, 510, 91, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.joints_lineedit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.joints_lineedit_4.setObjectName("joints_lineedit_4")
        self.horizontalLayout_4.addWidget(self.joints_lineedit_4)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(150, 390, 91, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.joints_lineedit_1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.joints_lineedit_1.setObjectName("joints_lineedit_1")
        self.horizontalLayout.addWidget(self.joints_lineedit_1)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(10, 240, 831, 30))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 131, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.dial_1 = QtWidgets.QDial(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_1.sizePolicy().hasHeightForWidth())
        self.dial_1.setSizePolicy(sizePolicy)
        self.dial_1.setAutoFillBackground(False)
        self.dial_1.setMinimum(-20)
        self.dial_1.setMaximum(20)
        self.dial_1.setNotchTarget(0.0)
        self.dial_1.setNotchesVisible(False)
        self.dial_1.setObjectName("dial_1")
        self.verticalLayout.addWidget(self.dial_1)
        self.motor_2_label = QtWidgets.QLabel(self.tab)
        self.motor_2_label.setGeometry(QtCore.QRect(150, 10, 131, 31))
        self.motor_2_label.setFrameShape(QtWidgets.QFrame.Box)
        self.motor_2_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.motor_2_label.setScaledContents(True)
        self.motor_2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.motor_2_label.setObjectName("motor_2_label")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(430, 50, 131, 151))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.dial_4 = QtWidgets.QDial(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_4.sizePolicy().hasHeightForWidth())
        self.dial_4.setSizePolicy(sizePolicy)
        self.dial_4.setAutoFillBackground(False)
        self.dial_4.setMinimum(-20)
        self.dial_4.setMaximum(20)
        self.dial_4.setNotchTarget(0.0)
        self.dial_4.setNotchesVisible(False)
        self.dial_4.setObjectName("dial_4")
        self.verticalLayout_4.addWidget(self.dial_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(150, 50, 131, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.dial_2 = QtWidgets.QDial(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_2.sizePolicy().hasHeightForWidth())
        self.dial_2.setSizePolicy(sizePolicy)
        self.dial_2.setAutoFillBackground(False)
        self.dial_2.setMinimum(-10)
        self.dial_2.setMaximum(10)
        self.dial_2.setProperty("value", 0)
        self.dial_2.setNotchTarget(0.0)
        self.dial_2.setNotchesVisible(False)
        self.dial_2.setObjectName("dial_2")
        self.verticalLayout_2.addWidget(self.dial_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(450, 210, 89, 25))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(11)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(590, 210, 89, 25))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(11)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.jog_joints = QtWidgets.QPushButton(self.tab)
        self.jog_joints.setGeometry(QtCore.QRect(150, 640, 91, 25))
        self.jog_joints.setObjectName("jog_joints")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(150, 590, 91, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.joints_lineedit_6 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        self.joints_lineedit_6.setObjectName("joints_lineedit_6")
        self.horizontalLayout_6.addWidget(self.joints_lineedit_6)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(310, 210, 89, 25))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(11)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(30, 210, 89, 25))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.motor_5_label = QtWidgets.QLabel(self.tab)
        self.motor_5_label.setGeometry(QtCore.QRect(570, 10, 131, 31))
        self.motor_5_label.setFrameShape(QtWidgets.QFrame.Box)
        self.motor_5_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.motor_5_label.setScaledContents(True)
        self.motor_5_label.setAlignment(QtCore.Qt.AlignCenter)
        self.motor_5_label.setObjectName("motor_5_label")
        self.motor_4_label = QtWidgets.QLabel(self.tab)
        self.motor_4_label.setGeometry(QtCore.QRect(430, 10, 131, 31))
        self.motor_4_label.setFrameShape(QtWidgets.QFrame.Box)
        self.motor_4_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.motor_4_label.setScaledContents(True)
        self.motor_4_label.setAlignment(QtCore.Qt.AlignCenter)
        self.motor_4_label.setObjectName("motor_4_label")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(150, 470, 91, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.joints_lineedit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.joints_lineedit_3.setObjectName("joints_lineedit_3")
        self.horizontalLayout_3.addWidget(self.joints_lineedit_3)
        self.motor_1_label = QtWidgets.QLabel(self.tab)
        self.motor_1_label.setGeometry(QtCore.QRect(10, 10, 131, 31))
        self.motor_1_label.setFrameShape(QtWidgets.QFrame.Box)
        self.motor_1_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.motor_1_label.setScaledContents(True)
        self.motor_1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.motor_1_label.setObjectName("motor_1_label")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(150, 430, 91, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.joints_lineedit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.joints_lineedit_2.setObjectName("joints_lineedit_2")
        self.horizontalLayout_2.addWidget(self.joints_lineedit_2)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(290, 50, 131, 151))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.dial_3 = QtWidgets.QDial(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_3.sizePolicy().hasHeightForWidth())
        self.dial_3.setSizePolicy(sizePolicy)
        self.dial_3.setAutoFillBackground(False)
        self.dial_3.setMinimum(-20)
        self.dial_3.setMaximum(20)
        self.dial_3.setNotchTarget(0.0)
        self.dial_3.setNotchesVisible(False)
        self.dial_3.setObjectName("dial_3")
        self.verticalLayout_3.addWidget(self.dial_3)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(710, 50, 131, 151))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.dial_6 = QtWidgets.QDial(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_6.sizePolicy().hasHeightForWidth())
        self.dial_6.setSizePolicy(sizePolicy)
        self.dial_6.setAutoFillBackground(False)
        self.dial_6.setMinimum(-20)
        self.dial_6.setMaximum(20)
        self.dial_6.setNotchTarget(0.0)
        self.dial_6.setNotchesVisible(False)
        self.dial_6.setObjectName("dial_6")
        self.verticalLayout_6.addWidget(self.dial_6)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(150, 550, 91, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.joints_lineedit_5 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.joints_lineedit_5.setObjectName("joints_lineedit_5")
        self.horizontalLayout_5.addWidget(self.joints_lineedit_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(730, 210, 89, 25))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(11)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.motor_3_label = QtWidgets.QLabel(self.tab)
        self.motor_3_label.setGeometry(QtCore.QRect(290, 10, 131, 31))
        self.motor_3_label.setFrameShape(QtWidgets.QFrame.Box)
        self.motor_3_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.motor_3_label.setScaledContents(True)
        self.motor_3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.motor_3_label.setObjectName("motor_3_label")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 210, 89, 25))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.motor_6_label = QtWidgets.QLabel(self.tab)
        self.motor_6_label.setGeometry(QtCore.QRect(710, 10, 131, 31))
        self.motor_6_label.setFrameShape(QtWidgets.QFrame.Box)
        self.motor_6_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.motor_6_label.setScaledContents(True)
        self.motor_6_label.setAlignment(QtCore.Qt.AlignCenter)
        self.motor_6_label.setObjectName("motor_6_label")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(570, 50, 131, 151))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.dial_5 = QtWidgets.QDial(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_5.sizePolicy().hasHeightForWidth())
        self.dial_5.setSizePolicy(sizePolicy)
        self.dial_5.setAutoFillBackground(False)
        self.dial_5.setMinimum(-20)
        self.dial_5.setMaximum(20)
        self.dial_5.setNotchTarget(0.0)
        self.dial_5.setNotchesVisible(False)
        self.dial_5.setObjectName("dial_5")
        self.verticalLayout_5.addWidget(self.dial_5)
        self.jog_pose = QtWidgets.QPushButton(self.tab)
        self.jog_pose.setGeometry(QtCore.QRect(20, 640, 91, 25))
        self.jog_pose.setObjectName("jog_pose")
        self.start = QtWidgets.QPushButton(self.tab)
        self.start.setGeometry(QtCore.QRect(20, 270, 101, 25))
        self.start.setObjectName("start")
        self.motor_1_label_3 = QtWidgets.QLabel(self.tab)
        self.motor_1_label_3.setGeometry(QtCore.QRect(20, 350, 91, 31))
        self.motor_1_label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.motor_1_label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.motor_1_label_3.setScaledContents(True)
        self.motor_1_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.motor_1_label_3.setObjectName("motor_1_label_3")
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(20, 550, 91, 41))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_13.addWidget(self.label_23)
        self.pose_lineedit_5 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_13)
        self.pose_lineedit_5.setObjectName("pose_lineedit_5")
        self.horizontalLayout_13.addWidget(self.pose_lineedit_5)
        self.home = QtWidgets.QPushButton(self.tab)
        self.home.setGeometry(QtCore.QRect(20, 310, 221, 25))
        self.home.setObjectName("home")
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(20, 430, 91, 41))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_14.addWidget(self.label_24)
        self.pose_lineedit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_14)
        self.pose_lineedit_2.setObjectName("pose_lineedit_2")
        self.horizontalLayout_14.addWidget(self.pose_lineedit_2)
        self.horizontalLayoutWidget_15 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(20, 510, 91, 41))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_15.addWidget(self.label_25)
        self.pose_lineedit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_15)
        self.pose_lineedit_4.setObjectName("pose_lineedit_4")
        self.horizontalLayout_15.addWidget(self.pose_lineedit_4)
        self.horizontalLayoutWidget_16 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(20, 470, 91, 41))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget_16)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_16.addWidget(self.label_27)
        self.pose_lineedit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_16)
        self.pose_lineedit_3.setObjectName("pose_lineedit_3")
        self.horizontalLayout_16.addWidget(self.pose_lineedit_3)
        self.horizontalLayoutWidget_17 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(20, 590, 91, 41))
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget_17)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_17.addWidget(self.label_28)
        self.pose_lineedit_6 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_17)
        self.pose_lineedit_6.setObjectName("pose_lineedit_6")
        self.horizontalLayout_17.addWidget(self.pose_lineedit_6)
        self.stop = QtWidgets.QPushButton(self.tab)
        self.stop.setGeometry(QtCore.QRect(140, 270, 101, 25))
        self.stop.setObjectName("stop")
        self.horizontalLayoutWidget_18 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_18.setGeometry(QtCore.QRect(20, 390, 91, 41))
        self.horizontalLayoutWidget_18.setObjectName("horizontalLayoutWidget_18")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_18)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_29 = QtWidgets.QLabel(self.horizontalLayoutWidget_18)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_18.addWidget(self.label_29)
        self.pose_lineedit_1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_18)
        self.pose_lineedit_1.setObjectName("pose_lineedit_1")
        self.horizontalLayout_18.addWidget(self.pose_lineedit_1)
        self.motor_1_label_4 = QtWidgets.QLabel(self.tab)
        self.motor_1_label_4.setGeometry(QtCore.QRect(150, 350, 91, 31))
        self.motor_1_label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.motor_1_label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.motor_1_label_4.setScaledContents(True)
        self.motor_1_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.motor_1_label_4.setObjectName("motor_1_label_4")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(120, 350, 20, 351))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.add_pose = QtWidgets.QPushButton(self.tab)
        self.add_pose.setGeometry(QtCore.QRect(20, 680, 89, 25))
        self.add_pose.setObjectName("add_pose")
        self.add_joints = QtWidgets.QPushButton(self.tab)
        self.add_joints.setGeometry(QtCore.QRect(150, 680, 89, 25))
        self.add_joints.setObjectName("add_joints")
        self.clear_queue = QtWidgets.QPushButton(self.tab)
        self.clear_queue.setGeometry(QtCore.QRect(20, 720, 221, 25))
        self.clear_queue.setObjectName("clear_queue")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(250, 270, 20, 471))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.run_queue_button = QtWidgets.QPushButton(self.tab)
        self.run_queue_button.setGeometry(QtCore.QRect(20, 760, 221, 25))
        self.run_queue_button.setObjectName("run_queue_button")
        self.queue_file_entry = QtWidgets.QLineEdit(self.tab)
        self.queue_file_entry.setGeometry(QtCore.QRect(410, 760, 201, 25))
        self.queue_file_entry.setObjectName("queue_file_entry")
        self.load_queue = QtWidgets.QPushButton(self.tab)
        self.load_queue.setGeometry(QtCore.QRect(280, 760, 131, 25))
        self.load_queue.setObjectName("load_queue")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(20, 130, 91, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_7.addWidget(self.lineEdit_7)
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(20, 290, 91, 41))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_11.addWidget(self.label_18)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_11.addWidget(self.lineEdit_11)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(20, 250, 91, 41))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_10.addWidget(self.lineEdit_10)
        self.IK_jog_button = QtWidgets.QPushButton(self.tab_2)
        self.IK_jog_button.setGeometry(QtCore.QRect(40, 380, 51, 25))
        self.IK_jog_button.setObjectName("IK_jog_button")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(20, 210, 91, 41))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_9.addWidget(self.lineEdit_9)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(20, 170, 91, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_8.addWidget(self.lineEdit_8)
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(20, 330, 91, 41))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_12.addWidget(self.label_19)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_12)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_12.addWidget(self.lineEdit_12)
        self.ena_straight_line = QtWidgets.QRadioButton(self.tab_2)
        self.ena_straight_line.setGeometry(QtCore.QRect(130, 60, 131, 23))
        self.ena_straight_line.setObjectName("ena_straight_line")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(140, 180, 61, 25))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(70, 330, 67, 17))
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(190, 50, 67, 17))
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(140, 150, 71, 17))
        self.label_22.setObjectName("label_22")
        self.IK_home_button = QtWidgets.QPushButton(self.tab_2)
        self.IK_home_button.setGeometry(QtCore.QRect(130, 20, 101, 25))
        self.IK_home_button.setObjectName("IK_home_button")
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setGeometry(QtCore.QRect(250, 10, 16, 391))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 20, 91, 25))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 60, 91, 25))
        self.pushButton_9.setObjectName("pushButton_9")
        self.motor_1_label_2 = QtWidgets.QLabel(self.tab_2)
        self.motor_1_label_2.setGeometry(QtCore.QRect(20, 100, 91, 31))
        self.motor_1_label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.motor_1_label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.motor_1_label_2.setScaledContents(True)
        self.motor_1_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.motor_1_label_2.setObjectName("motor_1_label_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.pushButton_4)
        Dialog.setTabOrder(self.pushButton_4, self.pushButton_5)
        Dialog.setTabOrder(self.pushButton_5, self.jog_joints)
        Dialog.setTabOrder(self.jog_joints, self.pushButton_3)
        Dialog.setTabOrder(self.pushButton_3, self.pushButton)
        Dialog.setTabOrder(self.pushButton, self.pushButton_6)
        Dialog.setTabOrder(self.pushButton_6, self.pushButton_2)
        Dialog.setTabOrder(self.pushButton_2, self.dial_5)
        Dialog.setTabOrder(self.dial_5, self.joints_lineedit_4)
        Dialog.setTabOrder(self.joints_lineedit_4, self.joints_lineedit_1)
        Dialog.setTabOrder(self.joints_lineedit_1, self.dial_4)
        Dialog.setTabOrder(self.dial_4, self.dial_2)
        Dialog.setTabOrder(self.dial_2, self.joints_lineedit_6)
        Dialog.setTabOrder(self.joints_lineedit_6, self.joints_lineedit_3)
        Dialog.setTabOrder(self.joints_lineedit_3, self.dial_3)
        Dialog.setTabOrder(self.dial_3, self.joints_lineedit_2)
        Dialog.setTabOrder(self.joints_lineedit_2, self.dial_6)
        Dialog.setTabOrder(self.dial_6, self.joints_lineedit_5)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_9.setText(_translate("Dialog", "J4"))
        self.joints_lineedit_4.setText(_translate("Dialog", "0"))
        self.label.setText(_translate("Dialog", "J1"))
        self.joints_lineedit_1.setText(_translate("Dialog", "0"))
        self.label_1.setText(_translate("Dialog", "0 rad/s"))
        self.motor_2_label.setText(_translate("Dialog", "Joint 2"))
        self.label_4.setText(_translate("Dialog", "0 rad/s"))
        self.label_2.setText(_translate("Dialog", "0 rad/s"))
        self.pushButton_4.setText(_translate("Dialog", "Enabled"))
        self.pushButton_5.setText(_translate("Dialog", "Enabled"))
        self.jog_joints.setText(_translate("Dialog", "Jog"))
        self.label_11.setText(_translate("Dialog", "J6"))
        self.joints_lineedit_6.setText(_translate("Dialog", "0"))
        self.pushButton_3.setText(_translate("Dialog", "Enabled"))
        self.pushButton.setText(_translate("Dialog", "Enabled"))
        self.motor_5_label.setText(_translate("Dialog", "Joint 5"))
        self.motor_4_label.setText(_translate("Dialog", "Joint 4"))
        self.label_8.setText(_translate("Dialog", "J3"))
        self.joints_lineedit_3.setText(_translate("Dialog", "0"))
        self.motor_1_label.setText(_translate("Dialog", "Joint 1"))
        self.label_7.setText(_translate("Dialog", "J2"))
        self.joints_lineedit_2.setText(_translate("Dialog", "0"))
        self.label_3.setText(_translate("Dialog", "0 rad/s"))
        self.label_6.setText(_translate("Dialog", "0 rad/s"))
        self.label_10.setText(_translate("Dialog", "J5"))
        self.joints_lineedit_5.setText(_translate("Dialog", "0"))
        self.pushButton_6.setText(_translate("Dialog", "Enabled"))
        self.motor_3_label.setText(_translate("Dialog", "Joint 3"))
        self.pushButton_2.setText(_translate("Dialog", "Enabled"))
        self.motor_6_label.setText(_translate("Dialog", "Joint 6"))
        self.label_5.setText(_translate("Dialog", "0 rad/s"))
        self.jog_pose.setText(_translate("Dialog", "Jog"))
        self.start.setText(_translate("Dialog", "Start"))
        self.motor_1_label_3.setText(_translate("Dialog", "POSE"))
        self.label_23.setText(_translate("Dialog", "B"))
        self.pose_lineedit_5.setText(_translate("Dialog", "90"))
        self.home.setText(_translate("Dialog", "Home"))
        self.label_24.setText(_translate("Dialog", "Y"))
        self.pose_lineedit_2.setText(_translate("Dialog", "0"))
        self.label_25.setText(_translate("Dialog", "A"))
        self.pose_lineedit_4.setText(_translate("Dialog", "0"))
        self.label_27.setText(_translate("Dialog", "Z"))
        self.pose_lineedit_3.setText(_translate("Dialog", "348.05"))
        self.label_28.setText(_translate("Dialog", "C"))
        self.pose_lineedit_6.setText(_translate("Dialog", "180"))
        self.stop.setText(_translate("Dialog", "Stop"))
        self.label_29.setText(_translate("Dialog", "X"))
        self.pose_lineedit_1.setText(_translate("Dialog", "174.39"))
        self.motor_1_label_4.setText(_translate("Dialog", "JOINTS"))
        self.add_pose.setText(_translate("Dialog", "Add"))
        self.add_joints.setText(_translate("Dialog", "Add"))
        self.clear_queue.setText(_translate("Dialog", "Clear queue"))
        self.run_queue_button.setText(_translate("Dialog", "Run queue"))
        self.load_queue.setText(_translate("Dialog", "Load queue"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Manual Control"))
        self.label_14.setText(_translate("Dialog", "X"))
        self.lineEdit_7.setText(_translate("Dialog", "174.39"))
        self.label_18.setText(_translate("Dialog", "B"))
        self.lineEdit_11.setText(_translate("Dialog", "90"))
        self.label_17.setText(_translate("Dialog", "A"))
        self.lineEdit_10.setText(_translate("Dialog", "0"))
        self.IK_jog_button.setText(_translate("Dialog", "Jog"))
        self.label_16.setText(_translate("Dialog", "Z"))
        self.lineEdit_9.setText(_translate("Dialog", "348.05"))
        self.label_15.setText(_translate("Dialog", "Y"))
        self.lineEdit_8.setText(_translate("Dialog", "0"))
        self.label_19.setText(_translate("Dialog", "C"))
        self.lineEdit_12.setText(_translate("Dialog", "180"))
        self.ena_straight_line.setText(_translate("Dialog", "Straight line"))
        self.label_22.setText(_translate("Dialog", "Velocity"))
        self.IK_home_button.setText(_translate("Dialog", "Home"))
        self.pushButton_8.setText(_translate("Dialog", "Start"))
        self.pushButton_9.setText(_translate("Dialog", "Stop"))
        self.motor_1_label_2.setText(_translate("Dialog", "Jog Pose"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "IK Control"))
